image:
  - Visual Studio 2022
     
install:  
  - git clone --depth 1 https://github.com/bkaradzic/bx
  - git clone --depth 1 https://github.com/bkaradzic/bimg
  - git clone --depth 1 https://github.com/bkaradzic/bgfx.git

before_build:
- cmd: cd bgfx
- cmd: ..\bx\tools\bin\windows\genie %TOOLS% --with-tools --with-dynamic-runtime --platform=x64 vs2022
  
build_script:
- cmd: msbuild .build\projects\vs2022\bgfx.sln /t:Clean,Build /p:Configuration=Release /p:Platform=x64
- cmd: msbuild .build\projects\vs2022\bgfx.sln /t:Clean,Build /p:Configuration=Debug /p:Platform=x64
- cmd: cd ..

after_test:
  - cmd: nuget pack bgfx_package.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: nuget