image:
  - Visual Studio 2022
  
install:  
  - git clone --depth 1 https://github.com/erincatto/box2d.git
  
before_build:
- cmd: cmake -H.\box2d -G "Visual Studio 17 2022" -A x64 -B./build_x64 -DCMAKE_DEBUG_POSTFIX="d" -DBOX2D_BUILD_TESTBED="OFF" -DBOX2D_BUILD_UNIT_TESTS="OFF" -DCMAKE_INSTALL_PREFIX=./package_x64
    
build_script:
- cmd: cmake --build build_x64 --target INSTALL --config Release
- cmd: cmake --build build_x64 --target INSTALL --config Debug
  
after_test:
  - cmd: nuget pack box2d_package.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production