image:
  - Visual Studio 2022
  
install:  
  - git clone --depth 1 https://github.com/skypjack/entt.git
  
before_build:
- cmd: cmake -H.\entt -G "Visual Studio 17 2022" -A Win32 -B./build_x86 -DCMAKE_INSTALL_PREFIX=./package_x86
- cmd: cmake -H.\entt -G "Visual Studio 17 2022" -A x64 -B./build_x64 -DCMAKE_INSTALL_PREFIX=./package_x64
    
build_script:
- cmd: cmake --build build_x86 --target ALL_BUILD --config Release
- cmd: cmake --build build_x64 --target ALL_BUILD --config Release
  
after_test:
  - cmd: nuget pack entt_package.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production