image:
  - Visual Studio 2022
  
install:  
  - git clone --depth 1 https://github.com/ValveSoftware/GameNetworkingSockets.git GameNetworkingSockets_CMakeLists\source
  
before_build:
- cmd: nuget sources add -name appveyor -source https://ci.appveyor.com/nuget/krzysztofmajor-ilnu72arcjgl -username %nuget_user% -password %nuget_password%
- cmd: nuget restore -PackagesDirectory ./GameNetworkingSockets_CMakeLists/packages
- cmd: nuget update packages.config -RepositoryPath ./GameNetworkingSockets_CMakeLists/packages
- ps: |
    [xml]$xmlElem = Get-Content -Path ./packages.config
    $env:protobuf = $xmlElem.packages.package | Where-Object id -eq 'fluid.protobuf' | ForEach-Object { $_.version }
    $env:openssl = $xmlElem.packages.package | Where-Object id -eq 'fluid.openssl' | ForEach-Object { $_.version }
    Write-Host "protobuf version" $env:protobuf
    Write-Host "openssl version" $env:openssl
- cmd: call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
- cmd: cmake -H.\GameNetworkingSockets_CMakeLists -G "Visual Studio 17 2022" -A x64 -B./build_x64 -DCMAKE_INSTALL_PREFIX=./package_x64 -DBUILD_STATIC_LIB="ON" -DBUILD_SHARED_LIB="OFF" -DBUILD_TESTS="OFF" -DProtobuf_USE_STATIC_LIBS="ON" -DCMAKE_DEBUG_POSTFIX="d"  -DPROTOBUF_VERSION=%protobuf%

    
build_script:
- cmd: cmake --build build_x64 --target INSTALL --config Debug
- cmd: cmake --build build_x64 --target INSTALL --config Release
  
after_test:
  - cmd: nuget pack GameNetworkingSockets_package.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: nuget
