image:
  - Visual Studio 2022
  
install:  
  - git clone --depth 1 https://github.com/icculus/physfs.git
  
before_build:
- cmd: cmake -H.\physfs -G "Visual Studio 17 2022" -A x64 -B./build_x64 -DCMAKE_DEBUG_POSTFIX="d" -DPHYSFS_BUILD_SHARED="OFF" -DPHYSFS_BUILD_TEST="OFF" -DPHYSFS_BUILD_DOCS="OFF" -DPHYSFS_ARCHIVE_GRP="OFF" -DPHYSFS_ARCHIVE_WAD="OFF" -DPHYSFS_ARCHIVE_HOG="OFF" -DPHYSFS_ARCHIVE_MVL="OFF" -DPHYSFS_ARCHIVE_QPAK="OFF" -DPHYSFS_ARCHIVE_SLB="OFF" -DPHYSFS_ARCHIVE_VDF="OFF" -DCMAKE_INSTALL_PREFIX=./package_x64
    
build_script:
- cmd: cmake --build build_x64 --target INSTALL --config Release
- cmd: cmake --build build_x64 --target INSTALL --config Debug
  
after_test:
  - cmd: nuget pack physfs_package.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: nuget