image:
  - Visual Studio 2022
  
install:  
  - git clone --branch 4.1 --depth 1 https://github.com/KrzysztofMajor/PhysX.git
  
before_build:
- cmd: cd physx\physx
- cmd: .\generate_projects.bat vc17win64
    
build_script:
- cmd: cmake --build compiler/vc17win64 --target INSTALL --config Debug
- cmd: cmake --build compiler/vc17win64 --target INSTALL --config Release
- cmd: cd ..\..
  
after_test:
  - cmd: nuget pack physx_package.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production