image:
  - Visual Studio 2022
  
install:  
  - git clone -b 3.6.x --depth 1 https://github.com/protocolbuffers/protobuf.git
  
before_build:
- cmd: cmake -H.\protobuf\cmake -G "Visual Studio 17 2022" -A x64 -B./build_x64 -DCMAKE_INSTALL_PREFIX=./package_x64 -Dprotobuf_BUILD_TESTS="OFF" -Dprotobuf_BUILD_EXAMPLES="OFF" -Dprotobuf_MSVC_STATIC_RUNTIME="OFF" -DCMAKE_DEBUG_POSTFIX="d"
    
build_script:
- cmd: cmake --build build_x64 --target INSTALL --config Debug
- cmd: cmake --build build_x64 --target INSTALL --config Release
  
after_test:
  - cmd: nuget pack protobuf_package.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: nuget
