image:
  - Visual Studio 2022
  
install:  
  - git clone --depth 1 https://github.com/floooh/sokol.git  
  - git clone --depth 1 https://github.com/floooh/sokol-tools-bin.git
    
build_script:
  - cmd: nuget pack sokol_package.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production