image:
  - Visual Studio 2022
  
install:  
  - git clone --depth 1 https://github.com/gabime/spdlog.git
  
before_build:
- cmd: cmake -H.\spdlog -G "Visual Studio 17 2022" -A x64 -B./build_x64 -DCMAKE_INSTALL_PREFIX=./package_x64 -DSPDLOG_BUILD_EXAMPLE="OFF" -DSPDLOG_BUILD_TESTS="OFF"
    
build_script:
- cmd: cmake --build build_x64 --target INSTALL --config Release
  
after_test:
  - cmd: nuget pack spdlog_package.nuspec -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: nuget
